// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytkekrfkderkkjgagoca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0a2VrcmZrZGVya2tqZ2Fnb2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5NDA2OTYsImV4cCI6MjA5MDUxNjY5Nn0.G1__sRrl1nhH6QttpSlOpTMV3CWl8IVKE5F_E6gVa_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});